### ISSUE TITLE
Substratum commits

### ISSUE THREAD

**Issue by mikalackis** [substratum/documentation#5]
I'm trying to add substratum to my own home-made ROM but i'm having problems picking up which commits should i cherry pick. Did I miss the info on how to actually identify a commit that is related to the changes substratum team made?

**Comment by nathanchance** [comment]
The commits will be labelled as something related to themes or OMS. For example, in frameworks/base, the first commit is OMS7-N: Support tagging resources as OK to overlay [1/11]: https://github.com/SubstratumResources/platform_frameworks_base/commit/dc2a533b19ff60ffc82766ef692023e1a9d8b167

Usually the commits are committed by me or Nick. It should be fairly obvious if you have knowledge about how to read commit history but I'll leave this issue open in case you have any questions.

**Comment by mikalackis** [comment]
Thanks for your quick reply. I managed to figure it out, got it running on my ROM as we speak but thanks anyways for clearing it out for me :) 

Thanks for the work, substratum is awesome!
